"""
debug_trace.py - a debugger-style trace of the REAL program, written as markdown.
CITS4403 - Raed

Run from src/:   python debug_trace.py 0.70 > ../PROGRAM_TRACE.md

It follows regional_cascade(closure) exactly as the program runs it: the data
being loaded (with file and line numbers), the model being built, one day of
routing with EVERY push() call and the five limits it checked, the scoring,
and Layer 3. Pushes are recorded by the model itself (OilNetworkModel.push_log),
so nothing here is a copy of the model's logic.
"""
import ast, os, sys
import numpy as np
import oil_model_data as D
import oil_network_model as NM
import production_cascade as PC

closed = float(sys.argv[1]) if len(sys.argv) > 1 else 0.70
open_frac = 1.0 - closed
HERE = os.path.dirname(os.path.abspath(__file__))
INF = 1e8
f2 = lambda x: "no limit" if x >= INF else f"{x:.2f}"


def lines_of(fname):
    """{variable or function name: line number} for top-level definitions in a file."""
    tree = ast.parse(open(os.path.join(HERE, fname)).read())
    out = {}
    for n in ast.walk(tree):                                   # methods inside the class too
        if isinstance(n, ast.FunctionDef):
            out.setdefault(n.name, n.lineno)
    for n in tree.body:
        if isinstance(n, ast.Assign):
            for t in n.targets:
                if isinstance(t, ast.Name):
                    out.setdefault(t.id, n.lineno)
        elif isinstance(n, (ast.FunctionDef, ast.ClassDef)):
            out[n.name] = n.lineno
    return out


L_data, L_net, L_pc = lines_of("oil_model_data.py"), lines_of("oil_network_model.py"), lines_of("production_cascade.py")
P = print

P(f"# Program trace — `regional_cascade({closed:.2f})`, Hormuz {closed:.0%} closed\n")
P("Generated by `src/debug_trace.py` from the real model. Every push below was recorded by "
  "the model itself while it ran.\n")

# ---------------------------------------------------------------------------
P("## Part 1 — Reading the data\n")
P("The first thing any part of the program does is `from oil_model_data import *`. Python opens "
  "`src/oil_model_data.py`, runs it top to bottom, and keeps every variable in memory. "
  "No calculation happens — these are just numbers being stored.\n")
P("| Variable | File : line | What it holds | Value |\n|---|---|---|---|")
rows = [
    ("PRODUCTION_BY_REGION", "each region's production, mb/d", f"NAmerica {D.PRODUCTION_BY_REGION['NAmerica']}, MidEast {D.PRODUCTION_BY_REGION['MidEast']}, China {D.PRODUCTION_BY_REGION['China']}, … (10 regions, total {sum(D.PRODUCTION_BY_REGION.values()):.1f})"),
    ("CONSUMPTION_BY_REGION", "each region's demand, mb/d", f"NAmerica {D.CONSUMPTION_BY_REGION['NAmerica']}, China {D.CONSUMPTION_BY_REGION['China']}, Europe {D.CONSUMPTION_BY_REGION['Europe']}, … (total {sum(D.CONSUMPTION_BY_REGION.values()):.1f})"),
    ("CIS_EAST_PRODUCTION", "East Siberia's export-only output", f"{D.CIS_EAST_PRODUCTION}"),
    ("CHOKEPOINTS", "(normal flow, capacity) per passage", f"Hormuz {D.CHOKEPOINTS['Hormuz']}, Malacca {D.CHOKEPOINTS['Malacca']}, Panama {D.CHOKEPOINTS['Panama']}, …"),
    ("SAUDI_EASTWEST_CAPACITY", "Saudi pipeline budget, mb/d", f"{D.SAUDI_EASTWEST_CAPACITY}"),
    ("CONTESTABLE_FRACTION", "share of each exporter's surplus sold spot", f"MidEast {D.CONTESTABLE_FRACTION['MidEast']}, NAmerica {D.CONTESTABLE_FRACTION['NAmerica']}, Africa {D.CONTESTABLE_FRACTION['Africa']}, …"),
    ("MIN_OPERATING_RATE", "refinery minimum running rate", f"{D.MIN_OPERATING_RATE}"),
    ("BASE_VOYAGE_DAYS", "typical voyage, for sizing the tanker fleet", f"{D.BASE_VOYAGE_DAYS}"),
    ("REGION_NCI", "refinery complexity (Nelson index)", f"NAmerica {D.REGION_NCI['NAmerica']}, China {D.REGION_NCI['China']}, Africa {D.REGION_NCI['Africa']}, …"),
    ("PRICE_ELASTICITY", "demand response to price", f"NAmerica {D.PRICE_ELASTICITY['NAmerica']}, China {D.PRICE_ELASTICITY['China']}, Africa {D.PRICE_ELASTICITY['Africa']}, …"),
    ("REGIONAL_RESERVES", "strategic reserve per region, Mb", f"China {D.REGIONAL_RESERVES['China']}, NAmerica {D.REGIONAL_RESERVES['NAmerica']}, …"),
    ("REGIONAL_DRAW_RATE", "max reserve draw, mb/d", f"China {D.REGIONAL_DRAW_RATE['China']}, NAmerica {D.REGIONAL_DRAW_RATE['NAmerica']}, …"),
]
for name, what, val in rows:
    P(f"| `{name}` | oil_model_data.py : {L_data.get(name,'?')} | {what} | {val} |")

P("\nThen `oil_network_model.py` is imported. Its top part **builds four more tables from that data** "
  "(still no simulation):\n")
P("| Variable | File : line | How it's built | Value |\n|---|---|---|---|")
P(f"| `ROUTES` | oil_network_model.py : {L_net['ROUTES']} | typed in: 37 routes, each (producer, consumer, passages, days, own limit) | e.g. `\"ME->China\": {NM.ROUTES['ME->China']}` |")
P(f"| `SHARED_PIPELINES` | oil_network_model.py : {L_net['SHARED_PIPELINES']} | pipeline budgets | {NM.SHARED_PIPELINES} |")
P(f"| `REGION_DEMAND` | oil_network_model.py : {L_net['REGION_DEMAND']} | a copy of CONSUMPTION_BY_REGION | China {NM.REGION_DEMAND['China']}, … |")
P(f"| `ORIGIN_SUPPLY` | oil_network_model.py : {L_net['ORIGIN_SUPPLY']} | each region's production, renamed `<region>_P`; East Siberia split out of CIS | CIS_P {NM.ORIGIN_SUPPLY['CIS_P']:.1f} (13.8 − 1.8), CISEast_P {NM.ORIGIN_SUPPLY['CISEast_P']}, MidEast_P {NM.ORIGIN_SUPPLY['MidEast_P']} |")

P(f"\nAnd `production_cascade.py` stores the Layer 3 tables: `SECTORS` (line {L_pc['SECTORS']}), "
  f"`OIL_DEPENDENCE` (line {L_pc['OIL_DEPENDENCE']}), `DEPENDS_ON` (line {L_pc['DEPENDS_ON']}), "
  f"`OPERABLE_MIN` = {PC.OPERABLE_MIN} (line {L_pc['OPERABLE_MIN']}).\n")

# ---------------------------------------------------------------------------
P(f"## Part 2 — `regional_cascade({closed:.2f})` starts\n")
P(f"Defined at production_cascade.py : {L_pc['regional_cascade']}. Line by line:\n")
P("```python\niv = intervention or {}          # no intervention -> {}\n"
  "old_pipes, old_demand = ...      # saved copies, to restore at the end\n"
  f"SHARED_PIPELINES['SaudiPipe'] = 7.0 + 0          # no bypass_extra -> unchanged\n"
  "REGION_DEMAND[r] = old_demand[r] * (1 - 0)       # no demand_cut -> unchanged\n"
  "m = NM.OilNetworkModel()          # -> Part 3\n"
  f"for _ in range(150):\n    unserved, _, _ = m.step(1.0 - {closed:.2f})   # -> step({open_frac:.2f}), Parts 4-5\n```\n")

# ---------------------------------------------------------------------------
m = NM.OilNetworkModel()
P(f"## Part 3 — Building the model: `m = OilNetworkModel()`\n")
P(f"`class OilNetworkModel` is at oil_network_model.py : {L_net['OilNetworkModel']}. Creating `m` runs its "
  "`__init__`, which stores these values **on the object** — `m`'s memory:\n")
P("| Attribute | Value after construction | Meaning |\n|---|---|---|")
P(f"| `m.hoarding` | {m.hoarding} | hoarding switched off |")
P(f"| `m.bid_steepness` | {m.bid_steepness} | the 4 in premium = 1 + 4 × (short/demand)² |")
P(f"| `m.premium` | every region 1.0 | nobody bidding yet |")
P(f"| `m.min_rate` | {m.min_rate} | refinery minimum |")
P(f"| `m.running` | every region 1.0 | all demand met so far |")
P(f"| `m.shut_count` | every region 0 | no refineries shut |")
P(f"| `m.order_mult` | every region 1.0 | ordering exactly what's needed |")
P(f"| `m.fleet` | {m.fleet:.1f} | tanker capacity, barrel-days = {sum(NM.ORIGIN_SUPPLY.values()):.1f} supply × {D.BASE_VOYAGE_DAYS} days × 1.25 |")
P(f"| `m.G` | graph, {m.G.number_of_nodes()} nodes, {m.G.number_of_edges()} edges | the routes as a graph, for reference |")
P(f"| `m.push_log` | None | the recorder — switched on below for this trace |\n")

# ---------------------------------------------------------------------------
m.push_log = []
unserved, used, delivered = m.step(open_frac)
log = m.push_log
P(f"## Part 4 — Day 1: `m.step({open_frac:.2f})` calls `m.allocate_flows({open_frac:.2f})`\n")
P(f"`step` is at oil_network_model.py : {L_net['step']} and `allocate_flows` at line {L_net['allocate_flows']}; "
  f"`push` is defined inside it at line {L_net['push']}. `allocate_flows` "
  "first creates its **working tallies** for the day — fresh every day:\n")
cap = {c: (D.CHOKEPOINTS[c][1] if D.CHOKEPOINTS[c][1] is not None else INF) for c in D.CHOKEPOINTS}
cap["Hormuz"] = D.CHOKEPOINTS["Hormuz"][0] * open_frac
P("| Tally | Starts as | Meaning |\n|---|---|---|")
P(f"| `cap` | Hormuz {cap['Hormuz']:.2f} (= 20.9 × {open_frac:.2f}), Suez {cap['Suez+SUMED']}, Panama {cap['Panama']}, straits: no limit | today's limit per passage |")
P("| `used` | 0 for every passage | oil sent through each passage so far today |")
P("| `delivered` | 0 for every region | oil each region has received so far |")
P("| `supply_left` | a copy of ORIGIN_SUPPLY | oil each producer still has |")
P("| `want` | demand × order_mult = demand | what each region asks for |")
P(f"| `pipe_left` | {dict(NM.SHARED_PIPELINES)} | pipeline budgets left today |")
P("| `fleet_used` | 0 | tanker capacity used today |")
P("| `route_flow` | 0 for every route | oil sent down each route today |\n")

P("### Step 1 — domestic first\n")
P("```python\nfor r in REGIONS:\n    take = min(supply_left[r + '_P'], want[r])\n"
  "    delivered[r] += take\n    supply_left[r + '_P'] -= take\n```\n")
P("| Region | supply_left before | want | take | delivered after | supply_left after |\n|---|---|---|---|---|---|")
dom = {}
for r in NM.REGIONS:
    s0 = NM.ORIGIN_SUPPLY[r + "_P"]; w = NM.REGION_DEMAND[r]; t = min(s0, w); dom[r] = t
    P(f"| {r} | {s0:.2f} | {w:.2f} | {t:.2f} | {t:.2f} | {s0 - t:.2f} |")

P("\n### Step 2 — split each exporter's surplus\n")
P("```python\nspot[o] = supply_left[o] * CONTESTABLE_FRACTION[region]\nsupply_left[o] -= spot[o]     # Stage 1 may only use the contracted part\n```\n")
P("| Producer | surplus | spot share | spot (held back) | contracted (supply_left now) |\n|---|---|---|---|---|")
for o in m.last_spot:
    tot = m.last_spot[o] + m.last_contracted[o]
    if tot > 0.005:
        P(f"| {o} | {tot:.2f} | {D.CONTESTABLE_FRACTION.get(o[:-2], 0):.2f} | {m.last_spot[o]:.2f} | {m.last_contracted[o]:.2f} |")

# replay tallies from the log to show running values
run_used = {c: 0.0 for c in D.CHOKEPOINTS}
run_del = dict(dom)
run_sup = dict(m.last_contracted)
stage = 1


def push_table(entries):
    global run_sup
    P("| # | Route | Asked for (still needs) | Producer has | Room on path | Tankers | Route/pipe room | **Sent** | After: path used | After: producer left | After: buyer received |")
    P("|---|---|---|---|---|---|---|---|---|---|---|")
    for i, e in entries:
        for c in e["cps"]:
            run_used[c] += e["sent"]
        run_sup[e["origin"]] = run_sup.get(e["origin"], 0.0) - e["sent"]
        run_del[e["dest"]] += e["sent"]
        path = ", ".join(f"{c} {run_used[c]:.2f}" for c in e["cps"] if cap[c] < INF) or "no limited passage"
        pipe = f" ({e['pipe']})" if e["pipe"] else ""
        P(f"| {i} | {e['route']} | {e['need']:.2f} | {e['producer_left']:.2f} | {f2(e['passage_room'])} | "
          f"{e['tanker_room']:.1f} | {f2(e['route_room'])}{pipe} | **{e['sent']:.2f}** | {path} | "
          f"{e['origin']} {run_sup[e['origin']]:.2f} | {e['dest']} {run_del[e['dest']]:.2f} |")


split = log.index("STAGE 2")
P("\n### Step 3 — Stage 1: contracted oil, fastest route first\n")
P("```python\nfor rname in sorted(ROUTES, key=lambda k: ROUTES[k][3]):   # shortest voyage first\n"
  "    dest = ROUTES[rname][1]\n    need = want[dest] - delivered[dest]\n    if need > 0:              # only if the buyer still needs oil\n"
  "        push(rname, need)\n```\n")
P("Every one of the 37 routes is looked at in order of voyage days, but `push` is only called when "
  "the route's buyer still needs oil. Each row is one real `push()` call. **Sent** is the smallest of "
  "the five limits to its left; the last three columns are the tallies after the push.\n")
push_table([(i + 1, e) for i, e in enumerate(log[:split])])
P(f"\nRoutes skipped in Stage 1 because their buyer needed nothing: "
  f"{len(NM.ROUTES) - split} of 37.\n")
P("Still short after Stage 1: " + ", ".join(f"**{r} {v:.2f}**" for r, v in m.last_stage1_shortfall.items() if v > 0.005) + "\n")

P("### Step 4 — Stage 2: spot oil, one queue\n")
P("The held-back spot oil is added back to `supply_left`. Each short region bids "
  "`premium = 1 + 4 × (short/demand)²`, stored in `m.premium` (the only part of the day kept on the object):\n")
for r, v in m.last_stage1_shortfall.items():
    if v > 0.005:
        P(f"- {r}: 1 + 4 × ({v:.2f}/{NM.REGION_DEMAND[r]:.1f})² = **{m.premium[r]:.2f}**")
P(f"\nThe queue (`m.last_bids`) has {len(m.last_bids)} entries — one per (short region, route to it), "
  "sorted by netback = premium − 0.01 × days. Walking down it:\n")
P("```python\nfor netback, rname in self.last_bids:\n    r = ROUTES[rname][1]\n    if shortfall[r] > 0:\n"
  "        shortfall[r] -= push(rname, shortfall[r])\n```\n")
for o in m.last_spot:
    run_sup[o] = run_sup.get(o, 0.0) + m.last_spot[o]
push_table([(i + 1, e) for i, e in enumerate(log[split + 1:])])

# the rebuilt tallies must match the model's own, or the tables above are wrong
assert all(abs(run_del[r] - delivered[r]) < 1e-9 for r in NM.REGIONS), "replay does not match the model"
assert all(abs(run_used[c] - used[c]) < 1e-9 for c in D.CHOKEPOINTS), "replay does not match the model"
P("\n*Check: the running tallies above end exactly where the model's own tallies did.*")

# ---------------------------------------------------------------------------
P("\n## Part 5 — Back in `step()`: scoring the day\n")
P("```python\neffective = got * (1 + 0.15 * width)     # width = (NCI - 5) / 16\n"
  "unserved[r] = max(0, demand - served)     # served = effective (no refinery shuts)\n```\n")
P("| Region | demand | got (delivered) | uplift | effective | **unserved** |\n|---|---|---|---|---|---|")
for r in NM.REGIONS:
    w = np.clip((D.REGION_NCI[r] - D.NCI_MIN) / (D.NCI_MAX - D.NCI_MIN), 0.02, 1)
    P(f"| {r} | {NM.REGION_DEMAND[r]:.2f} | {delivered[r]:.2f} | × {1+0.15*w:.3f} | {delivered[r]*(1+0.15*w):.2f} | **{unserved[r]:.2f}** |")
P("\n`step` returns `unserved`, `used` and `delivered`. All the working tallies from Part 4 are "
  "thrown away; tomorrow starts fresh.\n")

# days 2-150
m.push_log = None
for _ in range(149):
    u150, _, _ = m.step(open_frac)
same = all(abs(u150[r] - unserved[r]) < 1e-9 for r in unserved)
P("## Part 6 — Days 2 to 150\n")
P(f"The loop calls `m.step({open_frac:.2f})` 149 more times. Each day repeats Part 4 from fresh tallies. "
  f"Day 150 gives exactly the same shortfalls as day 1: **{same}** — nothing carries over that changes the result.\n")

# ---------------------------------------------------------------------------
P(f"## Part 7 — Back in `regional_cascade`: Layer 3 for every region\n")
P("```python\nfor r, short in unserved.items():\n    relief = 0                                  # no buffer, no reserves here\n"
  "    avail = 1 - short / demand[r]\n    sysl, sectors = run_production_cascade(avail)\n"
  "    out[r] = dict(oil_available=avail, systemic_loss=sysl, sectors=sectors)\n```\n")
P(f"`run_production_cascade` is at production_cascade.py : {L_pc['run_production_cascade']}.\n")
P("| Region | oil_available | systemic loss |\n|---|---|---|")
worst = None
for r in NM.REGIONS:
    oa = 1 - u150[r] / NM.REGION_DEMAND[r]
    sl = PC.run_production_cascade(oa)[0]
    worst = max(worst or (sl, r), (sl, r))
    P(f"| {r} | {oa:.3f} | {sl:.1%}{' — **systemic**' if sl > 0.10 else ''} |")
P(f"\n`regional_cascade` returns this table. `critical_blockade_intensity` looks only at the worst "
  f"row — **{worst[1]}, {worst[0]:.1%}** — and since it is {'above' if worst[0] > 0.10 else 'below'} 10%, "
  f"its next guess is a **{'lower' if worst[0] > 0.10 else 'higher'}** closure.\n")
P("Finally `regional_cascade` restores `SHARED_PIPELINES` and `REGION_DEMAND` from its saved copies "
  "(the `finally:` block), so the next call starts clean.")
